Revision: b0ecdfe1f818308a1f96b2e4cfd60cf638e48701
Patch-set: 2
File: logcat/logcat.cpp

986:13-986:20
Fri Aug 05 22:42:11 2016 +0000
Author: Xin Li <1116123@85c56323-6fa9-3386-8a01-6480fb634889>
UUID: d97e679c_e91f1d5d
Bytes: 70
I assume the call won't return an error if the id file does not exist?

986:13-986:20
Fri Aug 05 23:09:06 2016 +0000
Author: Mark Salyzyn <1032276@85c56323-6fa9-3386-8a01-6480fb634889>
Parent: d97e679c_e91f1d5d
UUID: d97e679c_89e8e90f
Bytes: 36
The error is file_ok will be 'false'

986:13-986:20
Fri Aug 05 23:39:31 2016 +0000
Author: Xin Li <1116123@85c56323-6fa9-3386-8a01-6480fb634889>
Parent: d97e679c_89e8e90f
UUID: d97e679c_448b9815
Bytes: 167
Right. Sorry I should've looked at the library code more carefully.

So the first time we pass down --id, we won't clear past logs. Is this the expected behavior then?

